spring:
  application:
    name: coupon-consumer
  data:
    redis:
      host: localhost
      port: 6380
server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true
management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus

